# Generated by Django 4.0.4 on 2022-07-07 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=30, verbose_name='Sexe')),
                ('email', models.EmailField(max_length=254, verbose_name='Courriel')),
                ('password', models.CharField(max_length=30, verbose_name='Mot de passe')),
                ('ami', models.ManyToManyField(to='applidjango.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_de_publication', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applidjango.personne')),
            ],
        ),
    ]
