# Generated by Django 4.0.4 on 2022-06-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscoop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
