# Generated by Django 4.0.4 on 2022-07-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], max_length=30, verbose_name='Sexe')),
                ('email', models.EmailField(max_length=254, verbose_name='Courriel')),
                ('password', models.CharField(max_length=30, verbose_name='Mot de passe')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monappli.utilisateur')),
                ('raison_sociale', models.CharField(max_length=30, verbose_name='Raison sociale')),
            ],
            bases=('monappli.utilisateur',),
        ),
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monappli.utilisateur')),
            ],
            bases=('monappli.utilisateur',),
        ),
    ]
