# Generated by Django 4.0.4 on 2022-07-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], max_length=30, verbose_name='Sexe')),
                ('email', models.EmailField(max_length=254, verbose_name='Courriel')),
                ('password', models.CharField(max_length=30, verbose_name='Mot de passe')),
                ('ami', models.ManyToManyField(to='monappli.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monappli.utilisateur')),
                ('service', models.CharField(choices=[('D', 'DIRECTION'), ('A', 'AUDIT'), ('I', 'INFORMATIQUE'), ('CPT', 'COMPTABILITÉ'), ('J', 'JURIDIQUE'), ('M', 'MARKETING'), ('CMC', 'COMMERCIAL'), ('COUR', 'COURRIER'), ('CM', 'COMMUNICATION')], max_length=30, verbose_name='Service')),
                ('poste', models.CharField(max_length=30, verbose_name='Poste')),
            ],
            bases=('monappli.utilisateur',),
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monappli.utilisateur')),
                ('cursus', models.CharField(max_length=30, verbose_name='Cusrsus')),
            ],
            bases=('monappli.utilisateur',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monappli.utilisateur')),
            ],
        ),
    ]
