# Generated by Django 4.0.4 on 2022-06-29 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('amis', models.ManyToManyField(to='webapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.utilisateur')),
                ('service', models.CharField(max_length=30)),
                ('poste', models.CharField(max_length=30)),
            ],
            bases=('webapp.utilisateur',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_de_publication', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.utilisateur')),
            ],
        ),
    ]
