# Generated by Django 4.0.4 on 2022-06-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_utilisateur_amis_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.utilisateur')),
                ('service', models.CharField(max_length=30)),
                ('poste', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.poste')),
            ],
            bases=('webapp.utilisateur',),
        ),
    ]
