# Generated by Django 4.0.4 on 2022-06-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_poste_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='amis',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
