# Generated by Django 4.0.4 on 2022-06-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='amis',
            field=models.ManyToManyField(default=None, to='appliweb.personne'),
        ),
    ]
