# Generated by Django 4.0.4 on 2022-06-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0002_alter_personne_amis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='amis',
            field=models.ManyToManyField(to='appliweb.personne'),
        ),
    ]
