# Generated by Django 4.0.4 on 2022-06-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0003_alter_personne_amis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='numero_inscription',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='telephone_fixe',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='telephone_mobile',
        ),
    ]
